import { ImageSourcePropType } from 'react-native';

export const images: {[key: string]: ImageSourcePropType} = {
  logo: require('../images/logo.png'),
  splash_background: require('../images/splash_background.png'),
  splash_background2: require('../images/splash_background2.png'),
  otp: require('../images/otp.png'),
  forgot: require('../images/forgot.png'),
  exp1: require('../images/exp1.png'),
  exp2: require('../images/exp2.png'),
  female: require('../images/female.png'),
  background: require('../images/background.png'),
  map: require('../images/map.png'),
  slide1: require('../images/slidebackground1.png'),
  slide2: require('../images/slidebackground2.png'),
  slide3: require('../images/slidebackground3.png'),
  task1: require('../images/task1.png'),
  taskdetail1: require('../images/taskdetail1.png'),
  profile: require('../images/profilepicture.png'),
  map2: require('../images/map2.png'),
  thread1: require('../images/thread1.jpg'),
  professional: require('../images/professional.png'),
  review1: require('../images/reviewImage.png'),
  certificate1: require('../images/certificate1.png'),
  certificate2: require('../images/certificate2.png'),
  cardBg: require('../images/Rectangle.png'),
  correct: require('../images/Group2.png'),
};
