export const baseUrl = 'https://predemo.site/Alltradeconnection';

export const endPoints = {
    signUp: '/api/user/signUp',
    verifyOtp: '/api/user/verifyOtp',
    resendOtp: '/api/user/resendOtp',
    createProfile: '/api/user/updateProfile',
    createLocation: '/api/user/createLocation',
    getAllServices: '/api/user/getAllCategory',
    createProfessionalProfile: '/api/user/updateProfile',
    resetPassword: '/api/user/setNewPassword',
    signIn: '/api/user/login',
    getAllProjects: '/api/user/getProjectByStatusOrProfileId',
    getAllProfessionalProjects: '/api/user/getProjectByStatus',
    getAllProjectLocations: '/api/user/getLocationByProfileId',
    createProject: '/api/user/createProject',
    updateProject: '/api/user/updateProject',
    getProjectById: '/api/user/getProject',
    getProposalByProjectIdOrStatus: '/api/user/getProposalByProjectIdOrStatus',
    getProposalByProposalId: '/api/user/getProposal',
    updateProposalByProposalIdAndStatus: '/api/user/updateProposal',
    updateProposalStatus: '/api/user/updateProposalStatus',
    updateProjectStatusById: '/api/user/updateStatus',
    reportByIdAndReason: '/api/user/reportedByUser',
    createReview: '/api/user/createReview',
    getReviewByUserIdOrProId: '/api/user/getReviewByUserIdOrProId',
    getProfile: '/api/user/getProfile',
    updateProfile: '/api/user/updateProfile',
    createSupport: '/api/user/createSupport',
    changePassword: '/api/user/resetPassword',
    getAllProProfile: '/api/user/getAllProProfile',
    searchProProfileByLocationAndCategory: '/api/user/getProProfileByLocationAndCategory',
    updateProjectStatusToInDiscussion: '/api/user/updateStatus',
    createProposal: '/api/user/createProposal',
    updateProposal: '/api/user/updateProposal',
    getProposal: '/api/user/getProposal',
};